#!/usr/bin/env bash
# Installs firewall; block all incoming except 22, 443, 80

sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
